### PR TITLE
Upgrade to Humble + Garden

### PR DESCRIPTION
**Pull request by chapulina**
* Part of https://github.com/osrf/buoy_sim/issues/81

WIP

### CODE REVIEW

**Comment by srmainwaring** [comment]
@chapulina I missed this PR while getting a version to build for macOS and duplicated the bulk of the work in #89 🙄.

I've closed that PR and extracted the main differences (which mostly have to do with dependencies on ros_gz_bridge and ros_gz_sim) into this commit https://github.com/srmainwaring/buoy_sim/commit/8c886be2259651ba7e164bc68cfe35d467014e50 which was obtained after merging a fork of `chapulina/humble_garden` with `main` and resolving conflicts, so it should be suitable for cherry-picking into this branch once `main` has been merged in.

Happy to help with testing for macOS if you need it.

**Comment by quarkytale** [comment]
Updated with your commit @srmainwaring, made some small changes to fix the errors I was getting. This should be now ready, will iterate as required after Gazebo Garden release.

**Comment by mjcarroll** [comment]
@andermi I'm down to one test that times out.  The `sc_commands_ros_feedback` doesn't want to pass locally or in CI.  In CI, I'm seeing a timeout.  Locally, I'm seeing:


```
34: [sc_commands_ros_feedback-1] /home/mjcarroll/workspaces/mbari/src/buoy_sim/buoy_tests/tests/sc_commands_ros_feedback.cpp:412: Failure
34: [sc_commands_ros_feedback-1] Value of: static_cast<bool>(node->status_ & buoy_interfaces::msg::SCRecord::PUMP_TOGGLE)
34: [sc_commands_ros_feedback-1]   Actual: true
34: [sc_commands_ros_feedback-1] Expected: false
34: [sc_commands_ros_feedback-1] SC Pump Toggle should be OFF
34: [sc_commands_ros_feedback-1] /home/mjcarroll/workspaces/mbari/src/buoy_sim/buoy_tests/tests/sc_commands_ros_feedback.cpp:412: Failure
34: [sc_commands_ros_feedback-1] Value of: static_cast<bool>(node->status_ & buoy_interfaces::msg::SCRecord::PUMP_TOGGLE)
34: [sc_commands_ros_feedback-1]   Actual: true
34: [sc_commands_ros_feedback-1] Expected: false
34: [sc_commands_ros_feedback-1] SC Pump Toggle should be OFF
```

**Comment by mjcarroll** [comment]
The only test failures here appear to be timeouts now @andermi

**Comment by andermi** [comment]
> The only test failures here appear to be timeouts now @andermi

I'll try the `do-release-upgrade` tomorrow and help you diagnose

**Comment by srmainwaring** [comment]
@mjcarroll this is looking good on macOS as well. There is one catch which is that the header for `gnuplot-iostream` is not found on macOS - and this is now required for the build.

As a workaround I've created a ros2 / ament build of https://github.com/dstahlke/gnuplot-iostream on this branch
https://github.com/srmainwaring/gnuplot-iostream/tree/srmainwaring/ros2. With this package included in the workspace and a minor tweak in the form of https://github.com/srmainwaring/buoy_sim/commit/6ec250fc9c084be30ad9776afa7c515da0945dca the humble-garden branch builds on macOS (provided the other ros2 humble dependencies are all built).

I may have missed a ros2 package for gnuplot-iostream elsewhere, but if it's not available is there any interest in upstreaming one?

**Pull request closed without merging**
