### PR TITLE
Swap buoy_all.yaml back to main

### PR DESCRIPTION
**Pull request by quarkytale**

### CODE REVIEW

**Comment by quarkytale** [comment]
So `pc_commands_ros_feedback` is intermittently failing with
```
35: ======================================================================
35: FAIL: test_termination (buoy_tests.PCCommandsROSTest)
35: ----------------------------------------------------------------------
35: Traceback (most recent call last):
35:   File "/github/home/ws/src/buoy_sim/buoy_tests/launch/pc_commands_ros_feedback.launch.py", line 61, in test_termination
35:     proc_info.assertWaitForShutdown(process=gazebo_test_fixture, timeout=600)
35:   File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/proc_info_handler.py", line 141, in assertWaitForShutdown
35:     assert success, "Timed out waiting for process '{}' to finish".format(process)
35: AssertionError: Timed out waiting for process '<launch_ros.actions.node.Node object at 0x7f2c4f375690>' to finish
```
When I re-run the jobs individually they pass.

**Review by andermi — APPROVED** [review]

**Comment by andermi** [comment]
woot

**Comment by andermi** [comment]
@quarkytale was there anything left to do here or can we merge?

**Comment by hamilton8415** [comment]
Great Dharini, let's merge this into main asap so it doesn't interfere with activities involveing merging main into branches...

**Comment by quarkytale** [comment]
Sorry I thought this went in during the meeting

**Pull request merged**
