### PR TITLE
Spring Cleaning :stuck_out_tongue_winking_eye: 

### PR DESCRIPTION
**Pull request by andermi**
Addresses #54 

TODO:

- [x] Documentation comments
- [x] cleanup debug prints
- [x] optimization/cleanup

### CODE REVIEW

**Comment by hamilton8415** [comment]
Spring cleaning, so clever.  :)

**Comment by andermi** [comment]
profiling results:
Screenshot from 2022-06-06 18-27-20

**Comment by andermi** [comment]
@chapulina I don't know if there's anything specific to review here... perhaps just general best practice? I made a pass at cleanup of the config constants

**Review by chapulina — APPROVED** [review]
Nice cleanup, nothing stood out as a potential problem

**Pull request merged**
