### PR TITLE
enable launch test using ROS2

### PR DESCRIPTION
**Pull request by andermi**
utilize `buoy_msgs/interface.hpp` and use `launch_testing` to allow sim to control `/clock` in ROS2 node plugins with `ros_ign_bridge`

### CODE REVIEW

**Comment by andermi** [comment]
fails until https://github.com/osrf/buoy_msgs/pull/13

**Comment by quarkytale** [comment]
Is it okay to have a gtest and a pytest having the same filename?

**Comment by andermi** [comment]
> the same filename?

they should be named something different

**Comment by andermi** [comment]
I realized I had an unused pytest file: `no_inputs.py` that might have been confusing.

**Comment by quarkytale** [comment]
Ohh then this pull request is showing no new changes to add, I'm confused.

**Comment by andermi** [comment]
> no new changes to add

Oops. I guess these changes snuck in through a merge to #68 which has already been merged to `main` now. I suppose I'll close this as:

merged via #68

**Comment by andermi** [comment]
> no new changes to add

Oops. I guess these changes snuck in through a merge to #68 which has already been merged to `main` now. I suppose I'll close this as:

merged via #68

**Pull request closed without merging**
