### PR TITLE
Example ROS bridge for electro-hydraulic PTO

### PR DESCRIPTION
**Pull request by chapulina**
Here's an example launch file that loads the electro-hydraulic PTO world and exposes all the Gazebo topics to ROS.

## Try it out

Launch the world:

```
ros2 launch buoy_gazebo electrohydraulic_pto.launch.py
```

Check that topics are available with ROS:

```
$ ros2 topic list
/battcurr_HydraulicRam
/deltaP_HydraulicRam
/loadcurr_HydraulicRam
/model/Hydraulics_Test/joint/HydraulicRam/BiasCurrent
/model/Hydraulics_Test/joint/HydraulicRam/RetractFactor
/model/Hydraulics_Test/joint/HydraulicRam/ScaleFactor
/model/Hydraulics_Test/joint/HydraulicRam/UserCommandedCurr
/parameter_events
/pistonvel_HydraulicRam
/retractfactor_HydraulicRam
/rosout
/rpm_HydraulicRam
/scalefactor_HydraulicRam
/targwindcurr_HydraulicRam
/windcurr_HydraulicRam
```

Listen to a topic with ROS, for example:

```
$ ros2 topic echo /loadcurr_HydraulicRam                                              
data: 2.2142660968671457e-15                                                                                                                
---                                                                                                                                         
data: -4.370744217940814e-15                                                                                                                
---                                                                                                                                         
data: 8.880699994828767e-16                                                                                                                 
---                                                                                                                                         
data: 2.0216033708164716e-15                                                                                                                
---                                                                                                                                         
data: 4.3921030007387785e-16
```

Publish to a topic with ROS, for example:

```
$ ros2 topic pub --once /model/Hydraulics_Test/joint/HydraulicRam/UserCommandedCurr std_msgs/msg/Float64 "{data: 3}"
publisher: beginning loop
publishing #1: std_msgs.msg.Float64(data=3.0)

[parameter_bridge-2] [INFO] [1650325732.031830191] [ros_ign_bridge]: Passing message from ROS std_msgs/msg/Float64 to Ignition ignition.msgs.Double (showing msg only once per type)
[ign gazebo-1] ## Adjusting UserCommanded Current 3
```

## Open question

I'm not sure if we're planning to expose the same topics for all worlds, or different worlds will expose different topics. Some things we may want to do:

* compose a launch file of smaller ones - for example, we could have:
    * Launch file to bridge the electro-hydraulic PTO
    * Launch file to bridge the pneumatic spring
    * Other launch files for other components
    * A top-level launch file that includes the others based on parameters
* make the model and joint names configurable as launch parameters

### CODE REVIEW

**Comment by andermi** [comment]
I could see loading plugins a la carte for a general use, configurable product of which MBARI's is a specific implementation. It would be nice to easily launch individual plugins for testing in isolation (or superposition) when modeling.

**Review by andermi — APPROVED** [review]
:+1:

**Comment by chapulina** [comment]
> It would be nice to easily launch individual plugins for testing in isolation (or superposition) when modeling.

I'll open a separate PR breaking this apart 👍🏽

**Comment by chapulina** [comment]
> It would be nice to easily launch individual plugins for testing in isolation (or superposition) when modeling.

* See #28

**Pull request merged**
