### PR TITLE
stub unused services

### PR DESCRIPTION
**Pull request by andermi**
Addresses #67

### CODE REVIEW

**Comment by andermi** [comment]
needs [NOT_IMPLEMENTED](https://github.com/osrf/buoy_msgs/blob/cdeb0578c3c1a6ae684615b7267d58cdd1f4a6e3/msg/PBCommandResponse.msg#L7) field from https://github.com/osrf/buoy_msgs/pull/13/files

**Comment by andermi** [comment]
ok, so I pulled in #57 and #69 to get some unit testing and requires https://github.com/osrf/buoy_msgs/pull/13

The basic test is for both python and cpp building on the basic test in #56 but I added an implementation of the `buoy_msgs/interface` to check `power_controller` data published on `/pc_record` from the ROS2 gazebo plugin

**Comment by andermi** [comment]
here -> https://github.com/osrf/buoy_sim/pull/68/commits/1bd69a23ed49829001d594829e1e65ec52d28f51
I added a NoOpController ROS2 node plugin to service all unimplemented buoy commands

**Review by chapulina — APPROVED** [review]
LGTM, I just have a few trivial comments.

+1 for the macros 😄

**Comment by andermi** [comment]
@chapulina I can't figure out what's going on with the failing checks. For some reason, it looks like the sim isn't running for 5000 iterations in CI, but it passes in my workspace when I have `andermi/stub_unused_services` for `buoy_sim`, and `main` for `buoy_msgs` and `buoy_examples`

**Pull request merged**
