### PR TITLE
Setup profiler

### PR DESCRIPTION
**Pull request by chapulina**
[Ignition Common's profiler](https://ignitionrobotics.org/api/common/4.4/profiler.html) is very handy to debug performance.

This PR just sets up the profiler and makes use of the existing profiling points.

See the snippet added to the README for how to enable and use it. In order to get profiling points coming from the Gazebo libraries themselves, they need to be compiled from source with `-DENABLE_PROFILER=1`.

Here's some example output. I was surprised to see that the `PolytropicPneumaticSpring` is taking up almost as much time as the physics' forward step.

buoy_profiler

### CODE REVIEW

**Comment by hamilton8415** [comment]
This is great, glad to see such a tool exists.  I was surprised that the ElectroHydraulicPTO plugin didn't win the award.  I know for sure there's some optimizations in there still to chase.

**Comment by andermi** [comment]
> the `PolytropicPneumaticSpring` is taking up almost as much time as the physics' forward step

Most likely my debug console printouts. I can remove most of them now.

**Comment by andermi** [comment]
@chapulina when I try this, I don't see SimulationRunner in the Remotery window

Screenshot from 2022-06-02 17-03-23

**Comment by chapulina** [comment]
> when I try this, I don't see SimulationRunner in the Remotery window

Did you compile all of Ignition Fortress from source with `-DENABLE_PROFILER=1`? If you haven't, you'll only see the profiling points from `buoy_gazebo`.

Other tips to navigate the UI may also help here. Use the scroll wheel to zoom in a bit more time-wise, and click on the `+` button a few times next to `Thread0` to see more lines. The `Pause` button on the top-right also helps.

**Comment by andermi** [comment]
> Did you compile all of Ignition Fortress from source

Ah, that's the issue. Thanks!

**Comment by andermi** [comment]
There, I fixed it! :1st_place_medal: 

Screenshot from 2022-06-06 18-15-59

**Review by andermi — APPROVED** [review]
:+1: 

It also might be worth mentioning that I had to run:
`colcon build --cmake-args ' -DBUILD_TESTING=true' ' -DENABLE_PROFILER=0'`
in my workspace to get `colcon test` to work again (even on other branches... since it's in the cmake in `build` in top level workspace)

**Comment by chapulina** [comment]
> It also might be worth mentioning that I had to run:

Ahh good call, it took me a while to figure that out the first time I needed it, it's definitely worth mentioning.

**Pull request merged**
